image: maven:3.3.9-jdk-8

pipelines:
  default:
    - step:
        script:
          - mvn --version
          - mvn clean install
          - mkdir -p ~/.ssh
          - echo $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
          - (umask 077 ; echo $SSH_KEY > ~/.ssh/id_rsa_enc)
          - (umask 077 ; base64 --decode ~/.ssh/id_rsa_enc > ~/.ssh/id_rsa)
          - scp -v modules/rest/target/*.?ar deploy@meta1.metasolutions.se:/var/www/entrystore.org/download/
