image: maven:3.6-jdk-11

options:
  max-time: 10

stepdefinitions:
  - build: &build
      name: Build
      caches:
        - maven
      script:
        - mvn --version
        - mvn clean install
        - rm -rf ~/.m2/repository/org/entrystore/
      artifacts:
        - modules/*/target/**
  - deploy: &deploy
      name: Deploy
      script:
        - gpg --version
        - echo $GPG_SIGN_KEY | base64 -d | gpg --import
        - gpg --list-secret-keys
        - export VERSION=`cat VERSION.txt`
        - echo $VERSION
        - export FILE_BASE="entrystore-rest-$VERSION"
        - echo $FILE_BASE
        - ( cd modules/rest-standalone/target/dist/ && tar czf ${FILE_BASE}.tar.gz * && sha256sum ${FILE_BASE}.tar.gz > ${FILE_BASE}.tar.gz.sha256 && gpg --clearsign --default-key 4C12C06EE69EBA383C1A47C61010232068FF1D01 ${FILE_BASE}.tar.gz.sha256 )
        - ( cd modules/rest/target/ && sha256sum ${FILE_BASE}.war > ${FILE_BASE}.war.sha256 && gpg --clearsign --default-key 4C12C06EE69EBA383C1A47C61010232068FF1D01 ${FILE_BASE}.war.sha256 )
        - scp -v modules/rest/target/{*.war,*.sha256.asc} modules/rest-standalone/target/dist/{*.tar.gz,*.sha256.asc} deploy@meta1.metasolutions.se:/var/www/entrystore.org/download/
        - if [ $BITBUCKET_BRANCH == "develop" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/develop.version" ; elif [ $BITBUCKET_BRANCH == "master" ]; then ssh deploy@meta1.metasolutions.se "echo $VERSION > /var/www/entrystore.org/download/latest.version" ; fi
  - dockerhub: &dockerhub
      name: Docker Hub
      script:
        - docker version
        - export VERSION=`cat VERSION.txt`
        - echo $VERSION
        - git clone git@bitbucket.org:metasolutions/docker.git
        - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        - cd docker/entrystore
        - ls -l
        - docker build --build-arg ENTRYSTORE_VERSION=$VERSION -t metasolutions/entrystore:$VERSION .
        - docker push metasolutions/entrystore:$VERSION
        - if [ $BITBUCKET_BRANCH == "develop" ]; then docker tag metasolutions/entrystore:$VERSION metasolutions/entrystore:develop ; docker push metasolutions/entrystore:develop ; fi
      services:
        - docker
      caches:
        - docker

pipelines:
  default:
    - step: *build
  branches:
    master:
      - step: *build
      - step: *deploy
    develop:
      - step: *build
      - step: *deploy
      - step: *dockerhub
