server.port: 8080

info.app.version: @project.version@


spring:
    mvc.problemdetails.enabled: false
    servlet.multipart:
        max-file-size: 12MB
        max-request-size: 12MB


entrystore:
    configuration.path: file:modules/rest-standalone/spring-boot/src/main/resources/entrystore.properties
    solr.url: http://localhost:8983/solr/entrystore-core

