
server.port: 8080

info.app.version: @project.version@


spring.mvc.problemdetails.enabled: false

entrystore:
    configuration.path: file:modules/rest-standalone/spring-boot/src/main/resources/entrystore.properties

