server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
#    context-path: /store
    session.cookie:
      name: auth_token
      http-only: ${entrystore.auth.cookie.httponly:true}
      secure: ${entrystore.auth.cookie.secure:true}
      same-site: ${entrystore.auth.cookie.samesite:strict}
      max-age: ${entrystore.auth.cookie.max-age:86400s}


info.app.version: "@project.version@"


# imported properties from "entrystore.properties" take precedence over properties here (when the same key exists in both property sources)
spring:
  config.import:
    - file:entrystore.properties
  mvc.problemdetails.enabled: false
  servlet.multipart:
    max-file-size: 12MB
    max-request-size: 12MB


springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true


management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: metrics
      discovery:
        enabled: false
  endpoint:
    metrics:
      access: read_only


logging:
  http:
    enabled: true   # Enabled is the default (i.e. when this property is not set), set it to "false" to disable request/response logging
